name:                toy-lambdas
version:             0.1.0.0
github:              "githubuser/toy-lambdas"
license:             BSD3
author:              "Ben Kushigian"
maintainer:          "bkushigian@gmail.com"
copyright:           "2019 Ben Kushigian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/toy-lambdas#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  toy-lambdas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-lambdas

tests:
  toy-lambdas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-lambdas
